name: 'Build PHP image'
#inputs:
#  PHP_VER:
#    required: true
#  TAGS:
#    required: true
#  DOCKER_USERNAME:
#    required: true
#  DOCKER_PASSWORD:
#    required: true
runs:
  using: "composite"
#  env:
#    PHP_VER: ${{ inputs.PHP_VER }}
  steps:
  - run: make
    shell: bash
  - run: make test
    shell: bash
  - name: Release image
#    env:
#      DOCKER_USERNAME: ${{ inputs.DOCKER_USERNAME }}
#      DOCKER_PASSWORD: ${{ inputs.DOCKER_PASSWORD }}
#      TAGS: ${{ inputs.TAGS }}
    run: . ./release.sh
    shell: bash
