name: 'Build PHP image'
inputs:
  version:
    required: true
  tags:
    required: true
  docker_username:
    required: true
  docker_password:
    required: true
runs:
  using: "composite"
  env:
    PHP_VER: ${{ inputs.version }}
  steps:
  - run: make
    shell: bash
  - run: make test
    shell: bash
  - name: Release image
    env:
      DOCKER_USERNAME: ${{ inputs.docker_username }}
      DOCKER_PASSWORD: ${{ inputs.docker_password }}
      TAGS: ${{ inputs.tags }}
    run: . ./release.sh
    shell: bash
