name: 'Build PHP image'
inputs:
  php:
    required: true
runs:
  using: composite
  steps:
  - run: make
  - run: make test
  - name: Release image
    env:
      DOCKER_USERNAME: ${{ inputs.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ inputs.DOCKER_PASSWORD }}
    run: . ./release.sh
