name: Build
description: Build PHP image
inputs:
  version:
    description: php version
    required: true
runs:
  using: "composite"
  steps:
  - name: Build image
    env:
      PHP_VER: ${{ inputs.version }}
    run: make
    shell: bash
  - name: Run tests
    env:
      PHP_VER: ${{ inputs.version }}
    run: make test
    shell: bash