name: Build
description: Build PHP image
inputs:
  version:
    description: php version
    required: true
  workdir:
    description: working directory
    required: true
  dev:
    description: dev version of image
    required: false
  user_id:
    description: user id
    required: false
  group_id:
    description: group id
    required: false
  tags:
    description: image tags
    required: true
  platform:
    description: docker platform
    required: false
    default: linux/amd64
runs:
  using: "composite"
  steps:
  - name: Build image
    env:
      PHP_VER: ${{ inputs.version }}
      PHP_DEV: ${{ inputs.dev }}
      WODBY_USER_ID: ${{ inputs.user_id }}
      WODBY_GROUP_ID: ${{ inputs.group_id }}
      PLATFORM: ${{ inputs.platform }}
      TAGS: ${{ inputs.tags }}
    run: |
      set -e
      make buildx-build-amd64
      make test
      make buildx-build
      . $GITHUB_ACTION_PATH/release.sh
    shell: bash
    working-directory: ${{ inputs.workdir }}
