name: Build docker image

on:
  push:
    branches:
    - master

    tags:
    - '*'

  pull_request:

env:
  PHP74: 7.4.12
  PHP73: 7.3.24
  PHP72: 7.2.34

jobs:
  php74:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: [${{ env.PHP74}}]
#        dev: ['',1]
#        user_id: ['',501]
#        include:
#        - user_id: 501
#          group_id: 501
#        exlude:
#        - user_id: 501
#          dev: ''
    defaults:
      run:
        working-directory: 7
    env:
      PHP_VER: 7.4.12
      TAGS: 7.4,7,latest
    steps:
    - uses: actions/checkout@v2
    - name: Build image
      run: make
    - name: Test
      run: make test
    - name: Release
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: . ../.github/workflows/release.sh
