name: Build docker image

on:
  push:
    branches:
    - master

    tags:
    - '*'

  pull_request:

env:
  PHP80: 8.0.2
  PHP74: 7.4.15
  PHP73: 7.3.26
  PHP72: 7.2.34

jobs:
  php80:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: '8'
    steps:
    - uses: actions/checkout@v2
    - uses: ./.github/actions
      with:
        version: ${{ env.PHP80 }}
        tags: 8.0,8,latest
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        workdir: 8
  php74:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: '7'
    steps:
    - uses: actions/checkout@v2
    - uses: ./.github/actions
      with:
        version: ${{ env.PHP74 }}
        tags: 7.4,7
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        workdir: 7
  php73:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: '7'
    steps:
    - uses: actions/checkout@v2
    - uses: ./.github/actions
      with:
        version: ${{ env.PHP73 }}
        tags: 7.3
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        workdir: 7
  php72:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: '7'
    steps:
    - uses: actions/checkout@v2
    - uses: ./.github/actions
      with:
        version: ${{ env.PHP72 }}
        tags: 7.2
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        workdir: 7
  ### dev
  php80-dev:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: '8'
    steps:
    - uses: actions/checkout@v2
    - uses: ./.github/actions
      with:
        version: ${{ env.PHP80 }}
        dev: 1
        tags: 8.0-dev,8-dev,dev
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        workdir: 8
  php74-dev:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: '7'
    steps:
    - uses: actions/checkout@v2
    - uses: ./.github/actions
      with:
        version: ${{ env.PHP74 }}
        dev: 1
        tags: 7.4-dev,7-dev
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        workdir: 7
  php73-dev:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: '7'
    steps:
    - uses: actions/checkout@v2
    - uses: ./.github/actions
      with:
        version: ${{ env.PHP73 }}
        dev: 1
        tags: 7.3-dev
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        workdir: 7
  php72-dev:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: '7'
    steps:
    - uses: actions/checkout@v2
    - uses: ./.github/actions
      with:
        version: ${{ env.PHP72 }}
        dev: 1
        tags: 7.2-dev
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        workdir: 7
  ### dev-macos
  php80-dev-macos:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: '8'
    steps:
    - uses: actions/checkout@v2
    - uses: ./.github/actions
      with:
        version: ${{ env.PHP80 }}
        dev: 1
        user_id: 501
        group_id: 20
        tags: 8.0-dev-macos,8-dev-macos,dev-macos
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        workdir: 8
  php74-dev-macos:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: '7'
    steps:
    - uses: actions/checkout@v2
    - uses: ./.github/actions
      with:
        version: ${{ env.PHP74 }}
        dev: 1
        user_id: 501
        group_id: 20
        tags: 7.4-dev-macos,7-dev-macos
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        workdir: 7
  php73-dev-macos:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: '7'
    steps:
    - uses: actions/checkout@v2
    - uses: ./.github/actions
      with:
        version: ${{ env.PHP73 }}
        dev: 1
        user_id: 501
        group_id: 20
        tags: 7.3-dev-macos
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        workdir: 7
  php72-dev-macos:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: '7'
    steps:
    - uses: actions/checkout@v2
    - uses: ./.github/actions
      with:
        version: ${{ env.PHP72 }}
        dev: 1
        user_id: 501
        group_id: 20
        tags: 7.2-dev-macos
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        workdir: 7
